### ISSUE TITLE
Does redis-kafka sink support thumbstones?

### ISSUE THREAD

**Issue by Casyfill** [redis-field-engineering/redis-kafka-connect#43]

**Comment by Casyfill** [comment]
larger piece of log:
```
ERROR [redis-sink|task-0] WorkerSinkTask{id=redis-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:233)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:635)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.redis.kafka.connect.shaded.io.lettuce.core.RedisException: java.lang.NullPointerException: Cannot invoke "org.apache.kafka.connect.data.Schema.type()" because the return value of "org.apache.kafka.connect.sink.SinkRecord.valueSchema()" is null
        at com.redis.kafka.connect.shaded.io.lettuce.core.internal.Exceptions.fromSynchronization(Exceptions.java:106)
        at com.redis.kafka.connect.shaded.com.redis.spring.batch.common.AbstractOperationExecutor.process(AbstractOperationExecutor.java:124)
        at com.redis.kafka.connect.shaded.com.redis.spring.batch.writer.AbstractOperationItemWriter.write(AbstractOperationItemWriter.java:47)
        at com.redis.kafka.connect.sink.RedisSinkTask.put(RedisSinkTask.java:328)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
        ... 11 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.kafka.connect.data.Schema.type()" because the return value of "org.apache.kafka.connect.sink.SinkRecord.valueSchema()" is null
        at com.redis.kafka.connect.sink.RedisSinkTask.map(RedisSinkTask.java:307)
        at com.redis.kafka.connect.shaded.com.redis.spring.batch.writer.operation.Hset.execute(Hset.java:23)
        at com.redis.kafka.connect.shaded.com.redis.spring.batch.writer.operation.AbstractKeyWriteOperation.execute(AbstractKeyWriteOperation.java:29)
        at com.redis.kafka.connect.shaded.com.redis.spring.batch.common.SimpleBatchOperation.execute(SimpleBatchOperation.java:21)
        at com.redis.kafka.connect.shaded.com.redis.spring.batch.common.AbstractOperationExecutor.process(AbstractOperationExecutor.java:117)
        ... 14 more
```

**Comment by Ching-Chieh-Wang** [comment]
same here when value is null
